'use strict';mix_d("ExportAlternativeWidgetCards__export-alternative-card-desktop:export-alternative-card-desktop__3KhWZN7s","exports tslib @c/remote-operations @c/tracking @p/jQuery @c/metrics".split(" "),function(r,t,x,y,z,g){function u(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var A=u(x),c=u(z),b;(function(a){a.DETAIL_DESKTOP_OUT_OF_STOCK="#exports_desktop_outOfStock_buybox_export_alternative_widget_ingress_feature_div";a.DETAIL_DESKTOP_UNQUALIFIED="#exports_desktop_unqualifiedBuybox_export_alternative_widget_ingress_feature_div";
a.DETAIL_DESKTOP_UNDELIVERABLE="#exports_desktop_undeliverable_buybox_cta_feature_div";a.DETAIL_MOBILE_OUT_OF_STOCK="#exports_mobile_outOfStock_buybox_export_alternative_widget_ingress_feature_div";a.DETAIL_MOBILE_UNQUALIFIED="#exports_mobile_unqualifiedBuybox_export_alternative_widget_ingress_feature_div";a.DETAIL_MOBILE_UNDELIVERABLE="#exports_mobile_undeliverable_buybox_cta_feature_div";a.DETAIL_MOBILEAPP_OUT_OF_STOCK="#exports_mobileapp_outOfStock_buybox_export_alternative_widget_ingress_feature_div";
a.DETAIL_MOBILEAPP_UNQUALIFIED="#exports_mobileapp_unqualifiedBuybox_export_alternative_widget_ingress_feature_div";a.DETAIL_MOBILEAPP_UNDELIVERABLE="#exports_mobileapp_undeliverable_buybox_cta_feature_div";a.TEST="#exportAlternativeWidgetTestMarker"})(b||(b={}));var m;(function(a){a.DISABLED_ATC="#exports-buybox-disabled-atc";a.SEE_ALL_BUYING_OPTIONS="#buybox-see-all-buying-choices"})(m||(m={}));var e;(function(a){a.TRIGGER_BUTTON="#exportAlternativeTriggerButton";a.TRIGGER_CONTENT=".export-alternative-trigger-content";
a.MODAL_PRELOAD="#a-popover-exportAlternativeModal";a.SHEET_PRELOAD="#exportAlternativeSheetPreloadContent";a.ASINS_INFO="#exportAlternativeAsinsInfo";a.CONTENT_TITLE="#exportAlternativeContentTitle";a.COUNTRY_CODE="#exportAlternativeShipToCountryCode";a.COUNTRY_NAME="#exportAlternativeShipToCountryName"})(e||(e={}));var h;(function(a){a.DETAIL_OUT_OF_STOCK="detail_out_of_stock";a.DETAIL_UNQUALIFIED="detail_unqualified";a.DETAIL_UNDELIVERABLE="detail_undeliverable";a.TEST="test"})(h||(h={}));var v;
(function(a){a.PRODUCT_API_ERROR="productApiError";a.ITEM_NOT_BUYABLE="itemNotBuyable";a.ITEM_NO_IMPORT_DETAILS="itemNoImportDetails";a.ITEM_NOT_DELIVERABLE="itemNotDeliverable";a.ITEM_MISSING_INFO="itemMissingInfo";a.PRICE_WRONG_FORMAT="priceWrongFormat";a.AGG_ERROR="aggregatedError"})(v||(v={}));var w;(function(a){a.FREE_SHIPPING="FREE_SHIPPING";a.UPSELL="UPSELL";a.NONE="NONE"})(w||(w={}));var d;(function(a){a.GET_CONTENT="exportAlternativeWidgetGetContent";a.TRIGGER_SHOW="exportAlternativeWidgetTriggerShow";
a.TRIGGER_CLICK="exportAlternativeWidgetTriggerClick";a.VARIANT_DETAIL_OUT_OF_STOCK="exportAlternativeWidgetVariantDetailOutOfStock";a.VARIANT_DETAIL_UNDELIVERABLE="exportAlternativeWidgetVariantDetailUndeliverable";a.VARIANT_DETAIL_UNQUALIFIED="exportAlternativeWidgetVariantDetailUnqualified";a.VARIANT_NOT_FOUND="exportAlternativeWidgetVariantNotFound";a.CONTENT_SUCCESS="exportAlternativeWidgetContentSuccess";a.CONTENT_FAILURE="exportAlternativeWidgetContentFailure";a.ITEM_COUNT="exportAlternativeWidgetItemCount";
a.ITEM_CLICK="exportAlternativeWidgetItemClick";a.ATC_CLICK="exportAlternativeWidgetAtcClick";a.ATC_SUCCESS="exportAlternativeWidgetAtcSuccess";a.ATC_FAILURE="exportAlternativeWidgetAtcFailure";a.MOBILE_POSTFIX="Mobile"})(d||(d={}));var B=function(a){var k=c["default"](e.TRIGGER_BUTTON);if(k.length){var f=a?d.MOBILE_POSTFIX:"";g.count(d.TRIGGER_SHOW+f,1);k.click(function(){return g.count(d.TRIGGER_CLICK+f,1)})}},C=function(){var a=c["default"](b.DETAIL_DESKTOP_OUT_OF_STOCK).length||c["default"](b.DETAIL_MOBILE_OUT_OF_STOCK).length||
c["default"](b.DETAIL_MOBILEAPP_OUT_OF_STOCK).length,k=c["default"](b.DETAIL_DESKTOP_UNQUALIFIED).length||c["default"](b.DETAIL_MOBILE_UNQUALIFIED).length||c["default"](b.DETAIL_MOBILEAPP_UNQUALIFIED).length,f=c["default"](b.DETAIL_DESKTOP_UNDELIVERABLE).length||c["default"](b.DETAIL_MOBILE_UNDELIVERABLE).length||c["default"](b.DETAIL_MOBILEAPP_UNDELIVERABLE).length;if(a)return g.count(d.VARIANT_DETAIL_OUT_OF_STOCK,1),h.DETAIL_OUT_OF_STOCK;if(k)return g.count(d.VARIANT_DETAIL_UNQUALIFIED,1),h.DETAIL_UNQUALIFIED;
if(f)return g.count(d.VARIANT_DETAIL_UNDELIVERABLE,1),h.DETAIL_UNDELIVERABLE;if(c["default"](b.TEST).length)return h.TEST;g.count(d.VARIANT_NOT_FOUND,1)},E=function(a,k){var f,b,l,n,D=JSON.stringify(null!==(f=c["default"](e.ASINS_INFO).data("asinsinfo"))&&void 0!==f?f:{});f=null!==(b=c["default"](e.CONTENT_TITLE).text())&&void 0!==b?b:"";b=null!==(l=c["default"](e.COUNTRY_CODE).text())&&void 0!==l?l:"";l=null!==(n=c["default"](e.COUNTRY_NAME).text())&&void 0!==n?n:"";var p=C();if(p){var q=k?d.MOBILE_POSTFIX:
"";g.count(d.GET_CONTENT+q,1);a({asinsInfo:D,contentTitle:f,countryCode:b,countryName:l},function(a,b){g.count(d.CONTENT_SUCCESS+q,1);switch(p){case h.DETAIL_UNQUALIFIED:a.outerHTML&&c["default"](m.SEE_ALL_BUYING_OPTIONS).removeClass("a-button-primary").addClass("a-button-base");break;case h.DETAIL_UNDELIVERABLE:a.outerHTML||c["default"](m.DISABLED_ATC).removeClass("aok-hidden");break;case h.TEST:a.outerHTML||c["default"](k?e.SHEET_PRELOAD:e.MODAL_PRELOAD).html('<span class="export-alternative-test-content-success"/>')}a.outerHTML&&
(c["default"](k?e.SHEET_PRELOAD:e.MODAL_PRELOAD).html(a.outerHTML),c["default"](e.TRIGGER_CONTENT).removeClass("aok-hidden"),B(k));null===b||void 0===b?void 0:b()},function(a,b){g.count(d.CONTENT_FAILURE+q,1);switch(p){case h.DETAIL_UNDELIVERABLE:c["default"](m.DISABLED_ATC).removeClass("aok-hidden")}null===b||void 0===b?void 0:b()})}},F=function(a,b){var f=b?d.MOBILE_POSTFIX:"",e=0;c["default"](".export-alternative-cta").each(function(b,k){e++;b=c["default"](k).children(":first");var h=b.data("asin"),
l=b.data("offerlistingid");h&&l&&c["default"](k).click(function(){g.count(d.ATC_CLICK+f,1);a({asin:""+h,offerListingId:""+l},function(a,b){g.count(d.ATC_SUCCESS+f,1);null===b||void 0===b?void 0:b();"app"===a.context.deviceSubType?location.replace("/gp/cart/view.html"):location.reload()},function(a,b){g.count(d.ATC_FAILURE+f,1);null===b||void 0===b?void 0:b()})})});g.count(d.ITEM_COUNT+"_"+e,1);c["default"](".export-alternative-product-link").each(function(a,b){return c["default"](b).click(function(){return g.count(d.ITEM_CLICK+
f,1)})})};r._operationNames=["getContent","addToCart"];r.card=function(){return t.__awaiter(void 0,void 0,void 0,function(){var a,b,c;return t.__generator(this,function(d){a=A["default"].setup();b=function(b,c,d){y.addTracking(a.addToCart,{},"ex_alt_wg_atc_d")(b).then(c).catch(d)};c=function(c,d,e){a.getContent(c).then(function(a){return d(a,function(){return F(b,!1)})}).catch(e)};E(c,!1);return[2]})})}});
